### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by ibex-of-entropy** [znetstar/tor-router#11]
```
cat@cate-ssd:~/Projects/tor-router$ npm run start

> tor-router@4.0.10 start /home/cat/Projects/tor-router
> bin/tor-router -s -d -j 1

info: [control]: control server listening on tcp://:9077
/home/cat/Projects/tor-router/node_modules/multi-rpc-tcp-transport/lib/TCPTransport.js:145
                this.server.off('error', listenError);
                            ^

TypeError: this.server.off is not a function
    at Server.listenSuccess (/home/cat/Projects/tor-router/node_modules/multi-rpc-tcp-transport/lib/TCPTransport.js:145:29)
    at Object.onceWrapper (events.js:272:13)
    at Server.emit (events.js:180:13)
    at emitListeningNT (net.js:1373:10)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tor-router@4.0.10 start: `bin/tor-router -s -d -j 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tor-router@4.0.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cat/.npm/_logs/2019-01-15T14_21_05_715Z-debug.log

```

**Comment by znetstar** [comment]
Hmmm, are you using a version of node below 10? The alias ".off" for ".removeListener" was added in v10 so I'm assuming that's why it's saying ".off" doesn't exist. I'm about to push a fix to master, when you can could you pull, run `npm install`, and let me know if it fixes the problem.
