### ISSUE TITLE
Not able to run tor-router with instances

### ISSUE THREAD

**Issue by prashant1507** [znetstar/tor-router#12]
when I am trying to run `tor-router -j 3 -s 127.0.0.1:16379` getting with `node v10.17.0` and `npm 6.13.0`

`info: [control]: control server listening on tcp://:9077
info: [tor]: starting 3 tor instance(s)...
info: [socks]: listening on socks5://127.0.0.1:16379
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/shibu/Downloads/node_modules/granax/bin/tor-browser_en-US/Browser/TorBrowser/Tor/tor ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

Can you please help me fixing the issue.

**Comment by jogli5er** [comment]
On which platform do you run it? Documentation by granax states that they only download the Tor Browser bundle on Mac and Windows, but on Linux one has to specify the path to the binary

**Comment by znetstar** [comment]
Situations like the one you've encountered are exactly why I recommend using Docker lol. As specified in the documentation using Docker you can run `docker run --rm -it -p 127.0.0.1:1637:9050 znetstar/tor-router -j 3 -s` and it should work without issue, since the Docker image bundles the correct version of Tor.

That being said, I'm assuming you're on Linux because of the reference to `/home/shibu`. Download tor through your package manager, `apt install tor` on Debian/Ubuntu or `yum install tor` on  Fedora/RedHat/Suse. You can then run `tor-router -t /usr/bin/tor -j 3 -s 127.0.0.1:16379`

**Comment by talha0324** [comment]
go to this path
`C:\Users\<user>\AppData\Roaming\npm\node_modules\tor-router\node_modules\@deadcanaries\granax\index.js`
this is according to global installation
and replace the line
```
  switch (platform) {
    case 'win32':
->      torpath = path.join(BIN_PATH, 'Browser', 'TorBrowser', 'Tor', 'tor.exe');
      break;
```
with this:
```
  switch (platform) {
    case 'win32':
      torpath = path.join(BIN_PATH, /*'Browser', 'TorBrowser', A FIX HERE */'Tor', 'tor.exe');
      break;
```

then there should be no error.
