### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by talha0324** [znetstar/tor-router#18]
Hi, I'm running the Docker image and sending a request via nodejs 
this is my code
```
import * as request from 'request';

request.get('http://example.com/', {
    proxy:'http://localhost:1637',    
},(e,r,b)=>{
    console.log(e)
    console.log(b)
    console.log(r)
})
```

this is my output of the code:

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
```

and these are my logs from Docker run:

```
>> docker run --rm -it -p 1637:9050 znetstar/tor-router -j 3 -h 127.0.0.1:9050

info: [control]: control server listening on tcp://:9077
info: [tor]: starting 3 tor instance(s)...
info: [tor-mXwaXKrDTKhS]: DNS PORT = 33353
info: [tor-mXwaXKrDTKhS]: SOCKS PORT = 46205
info: [tor-mXwaXKrDTKhS]: CONTROL PORT = 35985
info: [tor-ThoNeFBBQbV4]: DNS PORT = 42767
info: [tor-ThoNeFBBQbV4]: SOCKS PORT = 35143
info: [tor-ThoNeFBBQbV4]: CONTROL PORT = 40665
info: [tor-PL7fQWJDejLo]: DNS PORT = 34869
info: [tor-PL7fQWJDejLo]: SOCKS PORT = 37579
info: [tor-PL7fQWJDejLo]: CONTROL PORT = 44301
info: [http]: listening on http://127.0.0.1:9050
info: [tor-mXwaXKrDTKhS]: tor is ready
warn: [tor-PL7fQWJDejLo]: Unparseable microdescriptor

warn: [tor-PL7fQWJDejLo]: Illegal nickname "$B771AA877687F88E6F1CA5354756DF6C8A7B6B2" in family line

info: [tor-PL7fQWJDejLo]: tor is ready
info: [tor-ThoNeFBBQbV4]: tor is ready
info: [tor]: tor started
```

**Comment by talha0324** [comment]
got it working, was missing a `-s` flag
working command is this
`docker run --rm -it -p 1637:9080 znetstar/tor-router -j 3 -s -h`
then the http proxy will be available at `127.0.0.1:1637`
