### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by jogli5er** [znetstar/tor-router#4]
Hi,
I've run into the following issue and did not yet find a workaround.
Setup information: I run tor-router within a Docker container and on docker start, only the Control Server is initialized. 
Afterward, a Tor pool, a socket server and ten Tor instances are created in code (see below), which seems to work as expected, since the logs show
`
[control]: Control Server listening on 9077
[socks]: listening on 9050
[tor-19]: tor is ready
[tor-22]: tor is ready
`
Creation of Tor pool/socket server & Tor instances:
`    
    async createTorPool() {
        let rpcId = this.currentRPCId;
        this.currentRPCId += 1;
        let createTorRequest = {
            "method": "createTorPool",
            "params": [],
            "jsonrpc": "2.0",
            "id": rpcId,
        };
        this.client.write(JSON.stringify(createTorRequest));
        return new Promise( (resolve, reject) => {
            this.client.on("data", (chunk) => {
                let rawResponse = chunk.toString("utf8");
                let rpcResponse = JSON.parse( rawResponse );
                if (rpcResponse.id === rpcId) {
                    resolve(rpcResponse);
                }
            });
            // This runs on the same server. We wait a max of 255s for timeout
            setTimeout(() => {
                reject("createTorPool request timed out.");
            }, this.timeout);
        });
    }
    async createSocksServer(socksPort) {
        // Set torPort to 9050 (Tor standard), if undefined
        if (socksPort) {
            this.socksPort = socksPort;
        }
        if (!this.socksPort) {
            this.socksPort = 9050;
        }
        let rpcId = this.currentRPCId;
        this.currentRPCId += 1;
        let createSocksRequest = {
            "method": "createSOCKSServer",
            "params": [socksPort],
            "jsonrpc": "2.0",
            "id": rpcId,
        };
        this.client.write(JSON.stringify(createSocksRequest));
        return new Promise( (resolve, reject) => {
            this.client.on("data", (chunk) => {
                let rawResponse = chunk.toString("utf8");
                let rpcResponse = JSON.parse( rawResponse );
                if (rpcResponse.id === rpcId) {
                    resolve(rpcResponse);
                }
            });
            // This runs on the same server. We wait a max of 255s for timeout
            setTimeout(() => {
                reject("createSocksServer request timed out.");
            }, this.timeout);
        });
    }
    async createTorInstances(numOfInstances) {
        let rpcId = this.currentRPCId;
        this.currentRPCId += 1;
        let createTorInstancesRequest = {
            "method": "createInstances",
            "params": [numOfInstances],
            "jsonrpc": "2.0",
            "id": rpcId,
        };
        this.client.write(JSON.stringify(createTorInstancesRequest));
        return new Promise( (resolve, reject) => {
            this.client.on( "data", (chunk) => {
                let rawResponse = chunk.toString("utf8");
                let rpcResponse = JSON.parse( rawResponse );
                if (rpcResponse.id == rpcId) {
                    resolve(rpcResponse);
                }
            });
            setTimeout(() => {
                reject("createTorInstances timed out.");
            }, this.timeout);
        });
    }
`
However, if I send a request to the socks proxy (See codesection below), the logs say
`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TorPool.logPossibleMemoryLeak (/app/node_modules/eventemitter2/lib/eventemitter2.js:53:15)
    at TorPool.EventEmitter.on (/app/node_modules/eventemitter2/lib/eventemitter2.js:517:31)
    at TorPool.EventEmitter.many (/app/node_modules/eventemitter2/lib/eventemitter2.js:269:10)
    at TorPool.EventEmitter.once (/app/node_modules/eventemitter2/lib/eventemitter2.js:249:10)
    at SOCKSServer.handleConnection (/app/src/SOCKSServer.js:75:14)
    at emitThree (events.js:136:13)
    at SOCKSServer.emit (events.js:217:7)
    at Parser.<anonymous> (/app/node_modules/socksv5/lib/server.js:130:12)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
`
Code for sending the request over the SOCKS proxy:
`        let headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Encoding": "identity",
            "Connection": "keep-alive",
        };

        let request = {
            method: "GET",
            hostname: url,
            path: path,
            agent: new ProxyAgent("socks://127.0.0.1:9050"),
            headers: headers,
        };
        let startTime = (new Date).getTime();
        let request = http.get(request);
`
The same appears if I set the SOCKS proxy as the proxy of my browser and try to connect to a website.

So my question is: Is this an issue in my code and if yes: how should a request over this proxy be structured?

Thank you for your response!

**Comment by znetstar** [comment]
Hey Roman, could you tell me what version of Node you're using so I can try and re-create the issue. Thanks.

**Comment by jogli5er** [comment]
Sure, it's 9.4.0

**Comment by jogli5er** [comment]
Ok, so I did a bit of further debugging and found that within the SOCKSServer module, the tor_pool._instances is empty. This even though before when adding a tor instance, the _instances array contained the instance. I did not spot it yet, but I think it might be that we pass another tor_pool object tot the SOCKSServer than we use to create tor instances.

**Comment by jogli5er** [comment]
Ok, so if I boot up the tor-router and create the instances at this time it works. So I assume that it is the issue that the SOCKSServer and possibly the instances are added after the Control Server.
